### PR TITLE
Add on task removed override

### PR DESCRIPTION
**Pull request by mmaterowski**
I've found Your article about endless service very helpful, but in my case where I pressed 'Clear all recent apps' button service was stopped. Overriding onTaskRemoved and then restarting the service helped to resolve the issue. Sorry for indentation changes, my editor messes up formatting. Reject this PR and copy the method if You wish.
Cheers,
Michael

### CODE REVIEW

**Review by robertohuertasm — APPROVED** [review]
Hi @mmaterowski for this PR! I fixed the indentation issues. Please check that I've not messed up any of your code. Once you assure me everything is fine I'll proceed to merge it 👍🏻

**Comment by mmaterowski** [comment]
Looks great @robertohuertasm, I'm completing it :).

**Comment by robertohuertasm** [comment]
Why did you close it? Is it a mistake?

**Comment by mmaterowski** [comment]
Ahh sorry, missclicked it on the phone </3

**Comment by robertohuertasm** [comment]
😁 Glad you reopened it. So is there anything pending from your side? If not, I'll proceed with the merging.

**Comment by mmaterowski** [comment]
No, everything seems fine, you've got green light 😄!

**Comment by robertohuertasm** [comment]
Thanks a lot ❤️!

**Pull request merged**
